import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <div>
      <h1>This is Post Layout</h1>
      {children}
    </div>
  );
}
