import React from 'react';
import styles from '@styles/article.layout.module.scss'

export const metadata = {
  title: 'Using Query',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return (
    <div className={styles.container}>
      Loading from server (waiting page to be load)
    </div>
  );
}
